name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

# Ensure that the workflow is only triggered once per PR, subsequent pushes to the PR will cancel
# and restart the workflow. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run checks
        run: make -j check

  release:
    name: Release
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Login
        run: echo "${{ secrets.CARGO_REGISTRY_TOKEN }}" | cargo login

      - name: Publish (dry run)
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: make -j publish-dry-run

      - name: Publish
        id: publish
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: make -j publish

      - name: Build release (x86_64-unknown-linux-musl)
        run: make -j build-release

      - name: Build release (armv7-unknown-linux-musleabihf)
        run: make -j build-release-armv7

      - name: Package binaries
        run: |
          # Zip the binary, so it does not loose its executable flag when uploaded to GitHub Releases
          zip --junk-paths can-viewer-rs-x86_64-unknown-linux-musl.zip target/x86_64-unknown-linux-musl/release/can-viewer-rs
          zip --junk-paths can-viewer-rs-armv7-unknown-linux-musleabihf.zip target/armv7-unknown-linux-musleabihf/release/can-viewer-rs
          sha256sum can-viewer-rs-x86_64-unknown-linux-musl.zip > SHA256SUMS
          sha256sum can-viewer-rs-armv7-unknown-linux-musleabihf.zip >> SHA256SUMS
          cat SHA256SUMS

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ github.sha }}
          path: |
            can-viewer-rs-x86_64-unknown-linux-musl.zip
            can-viewer-rs-armv7-unknown-linux-musleabihf.zip
          retention-days: 1
          if-no-files-found: error

      - name: Publish to Github Release
        if: ${{ steps.publish.conclusion == 'success' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            can-viewer-rs-*.zip
            SHA256SUMS
          draft: true
          fail_on_unmatched_files: true
